FROM registry.access.redhat.com/ubi9/nodejs-18:1-118.1724037695 AS builder

WORKDIR /opt/app-root/src

COPY --chown=default:root . .

RUN mkdir -p /opt/app-root/src/node_modules && \
    npm ci && \
    npm run build

FROM registry.access.redhat.com/ubi9/nodejs-18:1-118.1724037695

WORKDIR /opt/app-root/src

COPY --from=builder --chown=default:root /opt/app-root/src/dist ./dist

WORKDIR /opt/app-root/src/server

COPY --chown=default:root ./server/* .

RUN npm ci && \
    chown -R default:root /opt/app-root/src/.npm && \
    chmod -R +w /opt/app-root/src/.npm

EXPOSE 8080

CMD ["npm", "start", "--", "--host"]
